[workspace]
members = [
    "crates/engine",
    "crates/testdata",
    "crates/wasmtime/v21",
    "crates/wasmtime/v41",
    "crates/benchmarks",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
wasmtime = { version = "21.0", package = "wasmtime-21" }
wasmtime-v41 = { version = "41.0", package = "wasmtime" }
criterion = "0.8"

