[package]
name = "wasmtime-v21"
version.workspace = true
edition.workspace = true

[dependencies]
engine = { path = "../../engine" }
testdata = { path = "../../testdata" }
wasmtime = { version = "21.0" }
anyhow = { workspace = true }